# Generated by Django 4.2.9 on 2024-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_medical_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='workout',
            field=models.CharField(max_length=555),
        ),
    ]
